### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by wuwenrufeng** [redfern314/southwest-search#6]
![image](https://user-images.githubusercontent.com/45844514/88366716-77762a80-cdbc-11ea-9d00-f7d513f2b898.png)
why empty?I've already replaced the ones that start with ee30zvqlwf.thanks!

**Comment by redfern314** [comment]
Hi @wuwenrufeng - make sure you're using a date in the future. I'm not sure Southwest's APIs will return any results for 2018.

Let me know if that doesn't work, something else might have broken in the code.
